Merge Dev to master
vlav98/lav-valentine-debug-Java pull request #1
Opened 2023-10-14 06:05 UTC by vlav98

2023-10-14 06:06 UTC, berrytchaks commented on Project02Eclipse/src/com/hemebiotech/analytics/AnalyticsCounter.java
> +	public static void main(String args[]) throws Exception {
A supprimer

2023-10-14 06:25 UTC, berrytchaks requested changes

2023-10-14 06:25 UTC, berrytchaks commented on Project02Eclipse/src/com/hemebiotech/analytics/AnalyticsCounter.java
> +		List<Map.Entry<String, Integer>> entryList = new ArrayList<>(symptoms.entrySet());
Ajouter dans une TreeMap.

2023-10-14 06:25 UTC, berrytchaks commented on Project02Eclipse/src/com/hemebiotech/analytics/ISymptomReader.java
> +	List<String> GetSymptoms();
```suggestion
	List<String> getSymptoms();

```

2023-10-14 06:25 UTC, berrytchaks commented on Project02Eclipse/src/com/hemebiotech/analytics/Main.java
> +    ISymptomReader reader = new ReadSymptomDataFromFile("symptoms.txt");
Déplacer les fichiers dans le dossier ressources (même niveau d'arborescence que le dossier src)

2023-10-14 06:25 UTC, berrytchaks commented on Project02Eclipse/src/com/hemebiotech/analytics/ReadSymptomDataFromFile.java
> +	public ReadSymptomDataFromFile(String filepath) {
```suggestion
	public ReadSymptomDataFromFile(String filePath) {

```

2023-10-14 06:25 UTC, berrytchaks commented on Project02Eclipse/src/com/hemebiotech/analytics/ReadSymptomDataFromFile.java
>  	private String filepath;
```suggestion
	private String filePath;

```

2023-10-14 06:25 UTC, berrytchaks commented on Project02Eclipse/src/com/hemebiotech/analytics/ReadSymptomDataFromFile.java
> +				BufferedReader reader = new BufferedReader(new FileReader(filepath));
Utiliser le try-with-ressources

2023-10-14 06:25 UTC, berrytchaks commented on Project02Eclipse/src/com/hemebiotech/analytics/ReadSymptomDataFromFile.java
>  		ArrayList<String> result = new ArrayList<String>();
```suggestion
		List<String> result = new ArrayList<>();

```

2023-10-14 06:25 UTC, berrytchaks commented on Project02Eclipse/src/com/hemebiotech/analytics/ReadSymptomDataFromFile.java
>  				e.printStackTrace();
```suggestion
				System.err.println("Error while reading file " + e.getMessage() + " caused by " + e.getCaused());

```

2023-10-14 06:25 UTC, berrytchaks commented on Project02Eclipse/src/com/hemebiotech/analytics/WriteSymptomDataToFile.java
> +				writer.close();
A virer

2023-10-14 06:25 UTC, berrytchaks commented on Project02Eclipse/src/com/hemebiotech/analytics/WriteSymptomDataToFile.java
> +			try (FileWriter writer = new FileWriter("result.out")) {
Utiliser la variable filePath. Utilser un `BufferedFileWriter`

2023-10-14 06:25 UTC, berrytchaks commented on Project02Eclipse/src/com/hemebiotech/analytics/WriteSymptomDataToFile.java
> + * Simple brute force implementation
Mettre le bon commentaire

2023-10-14 06:25 UTC, berrytchaks commented on Project02Eclipse/src/com/hemebiotech/analytics/WriteSymptomDataToFile.java
> +				e.printStackTrace();
Idem ici (syserr)

2023-10-17 21:18 UTC, berrytchaks approved these changes

2023-10-17 21:18 UTC, berrytchaks commented on Project02Eclipse/src/com/hemebiotech/analytics/AnalyticsCounter.java
> +		return sortedSymptoms;
```suggestion
		return new TreeMap<>(symptoms);

```

2023-10-17 21:18 UTC, berrytchaks commented on Project02Eclipse/src/com/hemebiotech/analytics/Main.java
> +    ISymptomReader reader = new ReadSymptomDataFromFile("./Project02Eclipse/resources/symptoms.txt");
Je déclarerai bien des constants pour ./Project02Eclipse/resources/symptoms.txt et ./Project02Eclipse/resources/result.out. Autrement dire, avant la fonction main je fais

```
private static final INPUT_FILE = "resources/symptoms.txt";
private static final OUTPUT_FILE = "resources/result.out";
```

Aussi le `./Project02Eclipse/` ne pas nécessaire.

2023-10-17 21:18 UTC, berrytchaks commented on Project02Eclipse/resources/result.out
> +water retention: 1
Je pense qu'il ne faut pas committé ce fichier. Je supprimerai bien ce fichier et afin d'éviter de le committer je rajouterai result.out dans le `.gitignore`

2023-10-19 09:52 UTC, vlav98 commented on Project02Eclipse/src/com/hemebiotech/analytics/Main.java
> +    ISymptomReader reader = new ReadSymptomDataFromFile("./Project02Eclipse/resources/symptoms.txt");
Quand je retire le `./Project02Eclipse` le code ne s'effectue pas et j'obtiens une erreur :
```
Error while reading file resources/symptoms.txt (No such file or directory) caused by null
Error while writing file resources/result.out (No such file or directory) caused by null
```

2023-10-27 06:26 UTC, merged